# **Numpy**

In [2]:
import numpy as np

In [3]:
np.sqrt(5)

2.23606797749979

# Arrays

## np.array()

In [7]:
a = [0,1,2,3,4,5,6,7,8,9,10]

type(a)

list

In [11]:
npA = np.array(a)
type(npA)

numpy.ndarray

## np.arange()

In [15]:
b = np.arange(4,24,2)
b

array([ 4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

## np.linspace()

In [19]:
c = np.linspace(1,50, 50)
c

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.])

## np.zeros()

In [23]:
h = np.zeros(10)
h

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## np.ones()

In [25]:
j = np.ones(10)
j

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# Dimensiones

In [29]:
array_2d = np.array([h,j])
array_2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

## array.shape

In [31]:
array_2d.shape

(2, 10)

## array.size

In [32]:
array_2d.size

20

## array.ndim

In [33]:
array_2d.ndim

2

# Operaciones con array

In [35]:
lista1 = [1,2,3,4,5]
lista2 = [6,7,8,9,10]

In [36]:
array1 = np.array(lista1)
array2 = np.array(lista2)

In [37]:
lista1 * lista2

TypeError: can't multiply sequence by non-int of type 'list'

In [38]:
array1 * array2

array([ 6, 14, 24, 36, 50])

# Funciones

## np.reshape()

In [44]:
array_2d.shape

(2, 10)

In [41]:
f = np.reshape(array_2d,(1,20))

In [42]:
f

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.]])

## np.T

In [49]:
a = np.array([[1,2,3,4,5],[10,20,30,40,50]])

In [50]:
a.T

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30],
       [ 4, 40],
       [ 5, 50]])

## np.random

### np.random.randintm

In [54]:
np.random.randint(0,300)

240

## np.where

In [55]:
array_2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [56]:
np.where(array_2d == 1,array_2d*10, array_2d-5)

array([[-5., -5., -5., -5., -5., -5., -5., -5., -5., -5.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.]])

# Estadistica

## distribuciones

In [59]:
array_normal = np.random.normal(1.75,0.05,1000)

In [60]:
array_normal

array([1.71678007, 1.71599359, 1.74124976, 1.72246257, 1.81434184,
       1.73824247, 1.72500408, 1.72427999, 1.80088184, 1.67284784,
       1.70018326, 1.78731781, 1.800648  , 1.70498672, 1.72872299,
       1.76042677, 1.7731646 , 1.72576271, 1.78367491, 1.70914418,
       1.82337247, 1.76768376, 1.79689308, 1.75319964, 1.74361528,
       1.77407404, 1.73516954, 1.79032097, 1.84269959, 1.72623148,
       1.73532609, 1.80062713, 1.72717537, 1.70745103, 1.77146719,
       1.7681687 , 1.7921039 , 1.80882783, 1.77566067, 1.77043522,
       1.75790492, 1.73899739, 1.71866565, 1.67777895, 1.76387125,
       1.68531127, 1.79330783, 1.70874173, 1.74333913, 1.74411047,
       1.73396219, 1.71562923, 1.72877609, 1.83838184, 1.64411175,
       1.85596556, 1.7398248 , 1.73432842, 1.78781671, 1.81711715,
       1.72368434, 1.84220147, 1.74212808, 1.6936074 , 1.7723486 ,
       1.74008859, 1.77297329, 1.85909447, 1.84350484, 1.78937603,
       1.64920566, 1.73208468, 1.76524845, 1.66672813, 1.77714

## np mean

In [62]:
np.mean(array_normal)

1.7505244173934813

## np median

In [63]:
np.median(array_normal)

1.7490119612443755

## np.std

In [65]:
np.std(array_normal)

0.05015623793399836